name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SHA: $(git rev-parse HEAD)
  GKE_CLUSTER: docker-react-test
  LOCATION: europe-west1
  IMAGE: docker-react

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t fracc/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true fracc/react-test npm test

      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/950268361153/locations/global/workloadIdentityPools/docker-react-test-pool/providers/docker-react-test-provider'
          service_account: 'udemy-doker-k8s@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

#      - name: Get Credentials
#        uses: google-github-actions/get-gke-credentials@v0
#        with:
#          cluster_name: ${{ env.GKE_CLUSTER }}
#          location: ${{ env.LOCATION }}

      - name: Build
        run: |-
          docker build -t fracc/multi-client ./client 
          docker build -t fracc/multi-nginx ./nginx
          docker build -t fracc/multi-server ./server 
          docker build -t fracc/multi-worker ./worker

      - name: Push
        run: |-
          docker push fracc/multi-client
          docker push fracc/multi-nginx
          docker push fracc/multi-server
          docker push fracc/multi-worker
